"ğŸŒ ç¿»è­¯":
- changed-files:
  - any-glob-to-any-file: "MultiVersions/**"

"â˜ï¸ å·¥ä½œæµç¨‹":
- changed-files:
  - any-glob-to-any-file: ".github/workflows/*"
  - any-glob-to-any-file: ".github/scripts/*"
  - any-glob-to-any-file: ".github/configs/*"

"ğŸ“ƒ æ–‡ä»¶":
- changed-files:
  - any-glob-to-any-file: "docs/*"
  - any-glob-to-any-file: "README.md"
