name: CI | Contributors Update

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  contributor-update:
    name: Contributors Update
    runs-on: ubuntu-latest
    if: github.repository == 'xMikux/ModsTranslationPack'

    steps:
      - name: Checking Repository
        uses: actions/checkout@v4

      - name: Generate Contributors Html Table
        id: html_list
        run: |
          list_html=$(cat <<-EOF
            python .github/scripts/contributors_generator.py
          EOF
          )
          {
            echo 'html_table<<EOF'
            $list_html
            echo EOF
          } >> "$GITHUB_OUTPUT"
          echo "::group::Html List"
          echo "$list_html"
          echo "::endgroup::"

          python .github/scripts/contributors_generator.py > html.list
          cat html.list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Readme
        run: |
          python .github/scripts/content_replacer.py
        env:
          FILE_PATH: "README.md"
          MULTILINE_MODE: true
          START_TAG: "<!-- CONTRIBUTORS_CI_START -->"
          END_TAG: "<!-- CONTRIBUTORS_CI_END -->"
          CONTENT: "${{ steps.html_list.outputs.html_table }}"

      - name: DEBUG
        run: |
          cat README.md

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      #     author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      #     title: "docs(Readme): æ›´æ–°è²¢ç»è€…æ¸…å–®"
      #     commit-message: "docs(Readme): æ›´æ–°è²¢ç»è€…æ¸…å–®"
      #     branch: docs/contributor-readme
      #     labels: |
      #       ğŸ“ƒ æ–‡ä»¶
      #     add-paths: README.md
      #     body: |
      #       è‡ªå‹•åŒ– [GitHub Action][github-action] å·¥ä½œæµç¨‹ï¼

      #       ------
      #       ç”± [create-pull-request][cpr] è‡ªå‹•ç”¢ç”Ÿ

      #       [cpr]: https://github.com/peter-evans/create-pull-request
      #       [github-action]: https://github.com/features/actions
