name: CI | Mods Counter

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  mods-counter:
    name: Mods Counter Update
    runs-on: ubuntu-latest
    if: |
      github.repository == 'xMikux/ModsTranslationPack'

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      - name: Count Mods
        id: mods
        run: | 
          NUMBER=$(python .github/scripts/mods_counter.py)
          echo "number=$NUMBER" >> "$GITHUB_OUTPUT"

      - name: Update Readme
        run: |
          python .github/scripts/content_replacer.py
        env:
          FILE_PATH: "README.md"
          MULTILINE_MODE: False
          START_TAG: "<!-- MODS_NUMBER_CI_START -->"
          END_TAG: "<!-- MODS_NUMBER_CI_END -->"
          CONTENT: "${{ steps.mods.outputs.number }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "docs(Readme): æ›´æ–°æ¨¡çµ„æ•¸é‡"
          commit-message: "docs(Readme): æ›´æ–°æ¨¡çµ„æ•¸é‡"
          branch: docs/mod-counter-readme
          labels: |
            ğŸ“ƒ æ–‡ä»¶
          add-paths: README.md
          body: |
            è‡ªå‹•åŒ– [GitHub Action][github-action] å·¥ä½œæµç¨‹ï¼

            ------
            ç”± [create-pull-request][cpr] è‡ªå‹•ç”¢ç”Ÿ

            [cpr]: https://github.com/peter-evans/create-pull-request
            [github-action]: https://github.com/features/actions
