name: CI | Pack - Beta

on:
  push:
    branches:
      - "main"
    paths:
      - "MultiVersions/**"
      - "!MultiVersions/README.md"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  matrix-setup:
    name: Setup Matrix
    if: github.repository == 'xMikux/ModsTranslationPack'
    uses: ./.github/workflows/Reusable-MatrixSetup.yml

  changelog-commit:
    name: Changelog Commit
    if: github.repository == 'xMikux/ModsTranslationPack'
    runs-on: ubuntu-latest

    outputs:
      changelog-commit: ${{ steps.commit.outputs.msg }}

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      - name: Format commit message
        id: commit
        run: |
          MSG=$(git show -s --format=%s)
          {
            echo 'msg<<EOF'
            python .github/scripts/commit_formater.py "$MSG"
            echo EOF
          } >> "$GITHUB_OUTPUT"

  verify-exist:
    name: Verify Version Exist
    if: github.repository == 'xMikux/ModsTranslationPack'

    uses: ./.github/workflows/Reusable-VerifyExistVersion.yml

  pack-beta:
    name: Pack ${{ matrix.version }}
    needs: [ matrix-setup ]

    strategy:
      matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix) }}

    uses: ./.github/workflows/Reusable-ResourcePacker.yml
    with:
      matrix_version: ${{ matrix.version }}
      release: false
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}

  summary:
    name: Generate Summary
    needs: [ pack-beta ]

    uses: ./.github/workflows/Reusable-Summary.yml

  modrinth-publish:
    name: Modrinth Beta ${{ matrix.version }}
    needs: [ pack-beta, matrix-setup, changelog-commit, verify-exist, summary ]
    if: ${{ needs.verify-exist.outputs.version_exist != 'true' }}

    strategy:
      max-parallel: 1
      matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix) }}

    runs-on: ubuntu-latest
    steps:
      - name: Hello Test
        run: |
          echo '${{ needs.changelog-commit.outputs.changelog-commit }}' >> test.md
          echo '\n---\n' >> test.md
          echo '${{ needs.summary.outputs.build_info }}' >> test.md
          cat test.md

    # uses: ./.github/workflows/Reusable-ModrinthPublish.yml
    # with:
    #   matrix_version: ${{ matrix.version }}
    #   changelog: | 
    #     ${{ needs.changelog-commit.outputs.changelog-commit }}

    #     ---
        
    #     ${{ needs.summary.outputs.build_info }}
    #   release: false
    # secrets:
    #   MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

  delete-artifact:
    name: Delete Artifact
    needs: [ modrinth-publish ]

    uses: ./.github/workflows/Reusable-DeleteArtifact.yml
    with:
      artifact_name: ModsTranslationPack-*
