name: CI | Pack - Release

## TODO - Unfinished
## Think a better way to do this.

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  matrix-setup:
    name: Setup Matrix
    if: github.repository == 'xMikux/ModsTranslationPack'
    uses: ./.github/workflows/Reusable-MatrixSetup.yml

  changelog-generate:
    name: Changelog Generate
    if: github.repository == 'xMikux/ModsTranslationPack'
    runs-on: ubuntu-latest

    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      - name: Get previous tag
        run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        # if: env.previous_tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          show-emoji: false
          remove-type: true
          template: |
            ## âš¡ æ–°å¢žæ¨¡çµ„ç¿»è­¯
            {{mods_feat}}
            ## ðŸŒ æ›´æ–°æ¨¡çµ„ç¿»è­¯
            {{mods_update}}
            ## ðŸ› ä¿®æ­£æ¨¡çµ„ç¿»è­¯éŒ¯èª¤
            {{mods_fix}}
            ## âœ¨ æå‡æ¨¡çµ„ç¿»è­¯å“è³ª
            {{mods_improve}}
            ## ðŸŒ ç”¨èªžåœ¨åœ°åŒ–
            {{mods_localize}}
            ## ðŸ§­ ç§»é™¤ç¿»è­¯
            {{mods_remove}}
            ## ðŸ“‘ æ–‡ä»¶æ›´æ–°
            {{docs}}
            ## ðŸ¤– å·¥ä½œæµç¨‹
            {{ci}}
            ## ðŸ§° é‡æ§‹
            {{refactor}}
            ## ðŸ§¹ æ¸…ç†å°ˆæ¡ˆ
            {{chore}}
            ## ðŸ”§ ä¿®æ­£å•é¡Œ
            {{fix}}
            ## ðŸ’ª æ–°å¢žåŠŸèƒ½
            {{feat}}
            ## ðŸ§° é‡æ§‹
            {{refactor,perf,clean}}
            ## å…¶ä»–
            {{__unknown__}}

      - name: æ¸¬è©¦ç”¢å‡º
        run: |
          echo ${{ steps.changelog.outputs.changelog }} > Test.md
          cat Test.md

  # pack-release:
  #   name: Pack ${{ matrix.version }}
  #   needs: [ matrix-setup ]

  #   strategy:
  #     matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix) }}

  #   uses: ./.github/workflows/Reusable-ResourcePacker.yml
  #   with:
  #     matrix_version: ${{ matrix.version }}
  #     release: true
  #   secrets:
  #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}

  # modrinth-publish:
  #   name: Modrinth Release ${{ matrix.version }}
  #   needs: [ pack-release, matrix-setup, changelog-generate ]

  #   strategy:
  #     max-parallel: 1
  #     matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix) }}
    
  #   uses: ./.github/workflows/Reusable-ModrinthPublish.yml
  #   with:
  #     version: $ input placeholder
  #     matrix_version: ${{ matrix.version }}
  #     changelog: ${{ needs.changelog-generate.outputs.changelog }}
  #     release: true
  #   secrets:
  #     MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

  # delete-artifact:
  #   name: Delete Artifact
  #   needs: [ modrinth-publish ]

  #   uses: ./.github/workflows/Reusable-DeleteArtifact.yml
  #   with:
  #     artifact_name: ModsTranslationPack-*
